/* Generated by Yosys 0.58+94 (git sha1 4011d7265, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

module blinky_synth(clk, led);
  input clk;
  wire clk;
  output led;
  wire led;
  wire _0_;
  wire _1_;
  wire _2_;
  wire [24:0] _3_;
  reg [24:0] _4_ = 25'h0000000;
  wire feedback;
  wire pll_clk;
  wire [24:0] r_count;
  assign _3_ = r_count + 25'h0000001;
  always @(posedge pll_clk)
    _4_ <= _3_;
  MMCME2_ADV #(
    .BANDWIDTH("OPTIMIZED"),
    .CLKFBOUT_MULT_F(10.625000),
    .CLKFBOUT_PHASE(0.000000),
    .CLKIN1_PERIOD(10.000000),
    .CLKOUT0_DIVIDE_F(20.875000),
    .CLKOUT0_PHASE(0.000000),
    .COMPENSATION("ZHOLD"),
    .DIVCLK_DIVIDE(32'd1),
    .REF_JITTER1(0.010000)
  ) mmcm_adv_inst (
    .CLKFBIN(feedback),
    .CLKFBOUT(_0_),
    .CLKIN1(clk),
    .CLKOUT0(_1_),
    .LOCKED(_2_),
    .PSINCDEC(1'h0),
    .PWRDWN(1'h0),
    .RST(1'h0)
  );
  assign pll_clk = _1_;
  assign feedback = _0_;
  assign r_count = _4_;
  assign led = r_count[24];
endmodule
