// t_compare.v -- comparison cells ($eq, $ne, $lt, $eqx) with y_width > 1
//
// Each cell type is exercised at two output widths:
//   y_width=4  (broken path): must produce one std_logic intermediate each
//   y_width=1  (control):     must stay as direct '1' when COND else '0'
//
// Operand pairs are rotated between y_width=4 and y_width=1 outputs so
// Yosys cannot merge them via CSE.
//
// $eqx (casex equality, generated by ===) has zero prior test coverage.
// $ne, $lt cover the ne/lt/le/ge/gt code path (all share the same template).
//
// Expected RTLIL: 4 x comparison cells at Y_WIDTH=4, 4 at Y_WIDTH=1.
// Expected VHDL after fix: 4 new 'signal nXX : std_logic;' declarations.
module t_compare (
    input  wire [3:0] vec_a, vec_b, vec_c,
    output wire [3:0] o_eq4,    // $eq  y_width=4  (broken before fix)
    output wire [3:0] o_ne4,    // $ne  y_width=4  (broken before fix)
    output wire [3:0] o_lt4,    // $lt  y_width=4  (broken before fix)
    output wire [3:0] o_eqx4,   // $eqx y_width=4  (broken before fix)
    output wire       o_eq1,    // $eq  y_width=1  (control: must be unchanged)
    output wire       o_ne1,    // $ne  y_width=1  (control: must be unchanged)
    output wire       o_lt1,    // $lt  y_width=1  (control: must be unchanged)
    output wire       o_eqx1    // $eqx y_width=1  (control: must be unchanged)
);
    assign o_eq4  = (vec_a == vec_b);   // $eq  Y_WIDTH=4
    assign o_ne4  = (vec_b != vec_c);   // $ne  Y_WIDTH=4
    assign o_lt4  = (vec_a <  vec_c);   // $lt  Y_WIDTH=4
    assign o_eqx4 = (vec_a === vec_b);  // $eqx Y_WIDTH=4

    assign o_eq1  = (vec_a == vec_c);   // $eq  Y_WIDTH=1 -- different pair
    assign o_ne1  = (vec_a != vec_b);   // $ne  Y_WIDTH=1 -- different pair
    assign o_lt1  = (vec_b <  vec_c);   // $lt  Y_WIDTH=1 -- different pair
    assign o_eqx1 = (vec_b === vec_c);  // $eqx Y_WIDTH=1 -- different pair
endmodule
