// t_pos_ext.v -- exercises $pos (zero/sign extension) cells.
//
// The $pos handler had a bug: the a_width != y_width branch emitted
//   Y <= std_logic_vector(resize(unsigned(A), N));
// which has type std_logic_vector(N-1 downto 0).  For y_width==1 this is
// std_logic_vector(0 downto 0) assigned to a std_logic target -- a GHDL
// type mismatch.  The fix uses arith_open/arith_close as every other
// arithmetic cell does.
//
// How to generate $pos cells from Verilog:
//   unary + on a signed value forces the frontend to emit a $pos cell.
//   The Y_WIDTH is set to the declared output width.
//
// Note: $pos with y_width==1 does not appear to be generated by the Verilog
// frontend (width mismatches to 1-bit outputs are resolved as RTLIL connect
// slices).  The y_width > 1 path exercises the same arith_open/close code
// path and confirms the fix is self-consistent.
module t_pos_ext (
    input  wire signed [3:0] s4,   // 4-bit signed input
    output wire        [7:0] o_sext, // sign-extend s4 4->8: $pos A_SIGNED=1 Y=8
    output wire        [3:0] o_id   // identity: $pos a_width==y_width (no-op path)
);
    assign o_sext = +s4;   // unary + on signed: $pos A_SIGNED=1 A_WIDTH=4 Y_WIDTH=8
    assign o_id   = +s4;   // same width: $pos A_WIDTH=4 Y_WIDTH=4 (identity path)
endmodule
