name: 'push'

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 5'

env:
  CI: true
  DOCKER_BUILDKIT: 1

jobs:

  test:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - run: ./ci.sh

    #- name: Trigger 'synth' in ghdl/docker
    #  if: github.ref == 'refs/heads/master' && github.event_name != 'pull_request'
    #  run: |
    #    curl -X POST https://api.github.com/repos/ghdl/docker/dispatches \
    #    -H "Content-Type: application/json" \
    #    -H 'Accept: application/vnd.github.everest-preview+json' \
    #    -H "Authorization: token ${{ secrets.GHDL_BOT }}" \
    #    --data '{"event_type": "synth"}'
